#!/bin/bash

cd /home/pi/feedtimer_system/configuration_app/ && python rtcTime.py & 

cd /home/pi/feedtimer_system/configuration_app/ && python feedTimer.py & 

cd /home/pi/feedtimer_system/configuration_app/server/ && sudo node app.js &

hostapd -dd /etc/hostapd/hostapd.conf &
