#!/bin/bash

python /home/pi/feedtimer_system/configuration_app/rtcTime.py & 

python /home/pi/feedtimer_system/configuration_app/feedTimer.py & 

sudo node /home/pi/feedtimer_system/configuration_app/server/app.js &

hostapd -dd /etc/hostapd/hostapd.conf &
