#!/bin/bash

python3 /usr/lib/raspiwifi/reset_device/reset.py &

su -c "cd /usr/lib/raspiwifi/configuration_app/ && rails s -b 0.0.0.0 -e production -p 9191 -d"

hostapd -dd /etc/hostapd/hostapd.conf &
